import { Catalog } from '../components/Catalog/Catalog';
import { Footer } from '../components/Footer/Footer';
import { Header } from '../components/Header/Header';
import { Hero } from '../components/Hero/Hero';
import { Subscribe } from '../components/Subscribe/Subscribe';
import Head from 'next/head';

export default function Home() {
	return (
		<div>
			<Head>
				<title>Create Next App</title>
				<meta name='description' content='Generated by create next app' />
				<link rel='icon' href='/favicon.ico' />
			</Head>

			<Header />
			<main>
				<Hero />
				<Catalog />
				<Subscribe />
			</main>
			<Footer />
		</div>
	);
}
