import { Catalog } from '../components/Catalog/Catalog';
import { Hero } from '../components/Hero/Hero';
import { Subscribe } from '../components/Subscribe/Subscribe';
import { MainLayout } from '../layouts/MainLayout/MainLayout';
import Head from 'next/head';

export default function Home() {
	return (
		<div>
			<Head>
				<title>Create Next App</title>
				<meta name='description' content='Generated by create next app' />
				<link rel='icon' href='/favicon.ico' />
			</Head>

			<MainLayout>
				<Hero />
				<Catalog />
				<Subscribe />
			</MainLayout>
		</div>
	);
}
