import { WriteForm } from '../components/WriteForm/WriteForm';
import { MainLayout } from '../layouts/MainLayout/MainLayout';
import { NextPage } from 'next';
import Head from 'next/head';
import React from 'react';

const WritePage: NextPage = () => {
	return (
		<div>
			<Head>
				<title>Create Next App</title>
				<meta name='description' content='Generated by create next app' />
				<link rel='icon' href='/favicon.ico' />
			</Head>
			<MainLayout>
				<WriteForm />
			</MainLayout>
		</div>
	);
};

export default WritePage;
